In [1]:
import tensorflow as tf
import numpy as np

Create rank 0 and rank 2 tensors

In [2]:
rank0_tensor = tf.constant(3)
rank0_tensor

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [3]:
rank1_tensor = tf.constant([1.0,2.0,3.0])
rank1_tensor



<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [4]:
rank2_tensor = tf.constant([[1,2],[3,4],[5,6]])
rank2_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

Printing Tensors

In [7]:
print(rank2_tensor)
tf.print(rank2_tensor)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
[[1 2]
 [3 4]
 [5 6]]


Reshaping Tensors

In [22]:
rowvector = tf.reshape(rank2_tensor,[6,1])
columnvector = tf.reshape(rank2_tensor, [1,6])
rowvector,columnvector

(<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
 array([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])>,
 <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6]])>)

Calculating with tensors

In [5]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2])`

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



getting values from a tensor

In [27]:
vector = tf.range(1,21)
matrix = tf.reshape(vector,[10,2])
matrix

<tf.Tensor: shape=(10, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])>

In [34]:
tf.print(matrix[1,:])
tf.print(matrix[:,1])
tf.print(matrix[-2,:])
tf.print(matrix[:,-2])

[3 4]
[2 4 6 ... 16 18 20]
[17 18]
[1 3 5 ... 15 17 19]


In [42]:
new_tensor = tf.zeros([3,3])
new_tensor



<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>