Import numpy, a python toolbox for numerical computations, and give it a abbreviation.



In [1]:
import numpy as np 

Create some arrays, which represent our tensors.

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
e_1 = np.array([1, 0, 0])
e_1

array([1, 0, 0])

In [4]:
e_2 = np.array([0, 1, 0])
e_2

array([0, 1, 0])

Matrix multiplication via the @ operator or explicitly.



In [5]:
a @ e_1

1

In [6]:
np.matmul(a, e_1)

1

Create higher dimensional arrays, which represent higher order tensors.

In [7]:
A = np.array([[1, 2, 3], [2, 5, 6], [3, 6, 9]])
A

array([[1, 2, 3],
       [2, 5, 6],
       [3, 6, 9]])

In [8]:
e_1 @ A @ e_2

2

Transpose via .T or as a function.

In [9]:
A.T

array([[1, 2, 3],
       [2, 5, 6],
       [3, 6, 9]])

In [10]:
np.transpose(A)

array([[1, 2, 3],
       [2, 5, 6],
       [3, 6, 9]])

In [11]:
B = A + 1
B

array([[ 2,  3,  4],
       [ 3,  6,  7],
       [ 4,  7, 10]])

Einsum lets you do quick tensor index calculation. Just enter the input indices and the desired output indices.

In [12]:
np.einsum("ik,kl->li", A, B)

array([[ 20,  43,  60],
       [ 36,  78, 108],
       [ 48, 103, 144]])

In [13]:
(A @ B).T

array([[ 20,  43,  60],
       [ 36,  78, 108],
       [ 48, 103, 144]])

In [14]:
B.T @ A.T

array([[ 20,  43,  60],
       [ 36,  78, 108],
       [ 48, 103, 144]])

In [15]:
np.einsum("ij,jl->li", A, B)

array([[ 20,  43,  60],
       [ 36,  78, 108],
       [ 48, 103, 144]])

In [16]:
np.einsum("ij,ij->", A, B)

242

In [17]:
B_anti = (1/2) * (B - B.T)
B_anti

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
B_sym = (1/2) * (B + B.T)
B_sym

array([[ 2.,  3.,  4.],
       [ 3.,  6.,  7.],
       [ 4.,  7., 10.]])

In [19]:
B_sym + B_anti

array([[ 2.,  3.,  4.],
       [ 3.,  6.,  7.],
       [ 4.,  7., 10.]])

In [20]:
np.equal(A, A.T)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [21]:
A = np.random.uniform(size=[3, 3])
print(A)

[[0.82419442 0.53459131 0.29075157]
 [0.9115608  0.12610662 0.18332464]
 [0.35347256 0.84452561 0.92768277]]


In [22]:
DIM = 3
B = np.zeros_like(A)
print(B)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
for i in range(DIM):
    for j in range(DIM):
        e_i = np.zeros([3,])
        e_j = np.zeros([3,])

        e_i[i] = 1
        e_j[j] = 1

        B[i, j] = np.dot(np.dot(e_i, A), e_j)

print(B)

[[0.82419442 0.53459131 0.29075157]
 [0.9115608  0.12610662 0.18332464]
 [0.35347256 0.84452561 0.92768277]]


In [24]:
print(np.isclose(A, B))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [25]:
a = np.random.uniform(size=[3,])
print(a)

[0.26161667 0.08774817 0.36672604]


In [26]:
e_1 = np.array([1, 0, 0])
print(e_1)

[1 0 0]


In [27]:
a_i = np.einsum('i,i -> i', a, e_1)
print(a_i)

[0.26161667 0.         0.        ]
